layout_spectrum: 0.7704931
typography_spectrum: 0.9282762
color:
  lightness: 1
  brandStrength: 0.163575
  saturation: 0.3903879
  rhythmicContrast: 0.3026981
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: 'Uptown Girl Soap & Bath Products'
