layout_spectrum: 0.8591906
name: 'Uptown Girl Soap & Bath Products'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.163575
  lightness: 0.01349073
  saturation: 0.886172
  rhythmicContrast: 0.4173693
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
typography_spectrum: 0.7099494
